title: Gitobi Blog
description: >- # this means to ignore newlines until "baseurl:"
  IoTとAIを利用したフルーツ工場事業を行っている、Gitobi合同会社のブログです。
author: Gitobi LLC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.gitobi.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: gitobi
twitter_username: gitobi_

# Build settings
markdown: kramdown
theme: minima
lang: ja
plugins:
  - jekyll-feed

exclude:
  - vendor
  - aws_secrets.env
  - aws_secrets.env.sample
  - deploy.sh
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
